### ISSUE TITLE
Module Request: TCL Roku tv control

### ISSUE THREAD

**Issue by Dwvsplat** [bitfocus/companion-module-roku-tv#1]
Need: power on/off
Source input (with delay timer) 
Volume control

**Comment by moofur** [comment]
@Dwvsplat @josephdadams Flashing the CompanionPi image is the recommended mode for Raspberry Pi usage. Once you've got that going, just run `sudo companion-update` in an SSH terminal and it'll update to the latest and greatest.

_The companion-update command is exclusive to the CompanionPi image and is not part of the main Companion source code. The command will not function outside of the CompanionPi build._

Information about CompanionPi can be found in the wiki: https://github.com/bitfocus/companion/wiki/CompanionPi-Documentation

**Comment by josephdadams** [comment]
@Dwvsplat did you give that a run?

**Comment by Dwvsplat** [comment]
Yep, it worked perfectly... It for the help!

**Comment by josephdadams** [comment]
That’s great! Happy to be able to serve you!

**Comment by Dwvsplat** [comment]
How do I get the stream deck to work with my raspberry pi?
I keep getting this error message:

 USB(undefined): Found device, but no access. Please quit any other
applications using the device, and try again

I have tried restarting, updating, and clearing with no success.

**Comment by josephdadams** [comment]
@jarodwsams any input here?

**Comment by moofur** [comment]
@Dwvsplat The issue is that you have one of the newer 15-button Stream Decks and the CompanionPi image doesn't include the hardware rules for that one. It's a simple fix.

1. In an SSH terminal window, `sudo nano /etc/udev/rules.d/50-companion.rules`
2. Delete all current contents of that file and replace with the following (copy/paste is your best friend)  
```SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
```

3. Reboot your Pi and you should be good to go

**Comment by moofur** [comment]
As soon as v2 is officially released from beta I'll drop an updated image and this fix will be included.

**Comment by Dwvsplat** [comment]
Thanks, that fixed it!
