### ISSUE TITLE
dynamic command/parameters in Send A Custom Command enhancement request

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-roku-tv#10]
Presently if I send a command to play a particular YouTube stream, as in 
`/launch/837?contentID=Y_L3n1pacE0`
The Roku opens up the YouTube app and plays that stream, as expected.

What I would like to be able to do is put **Y_L3n1pacE0** into a variable, so that 
`/launch/837?contentID=$(internal:custom_mystream)`
would do the same thing, as long as that custom variable was set to **Y_L3n1pacE0**
RIght now - on v3.1.2 (3.1.2+6243-stable-05c37a10) - that substitution does not seem to work.

**Comment by josephdadams** [comment]
If you can throw me a few bucks I can get this done for you pretty quickly
