### ISSUE TITLE
Button press actions not available in Companion 3.2.0

### ISSUE THREAD

**Issue by shaunar2006** [bitfocus/companion-module-roku-tv#12]
Existing actions are working, but cannot create new button presses ect. It shows "No Options" in the dropdown menu. I would like to use Companion 3.2.0, but this issue has caused me to have to rollback to 3.1.2. Here is the dropdown menu in 3.2.0:

![420955638_10224181993393208_3495731928871005628_n](https://github.com/bitfocus/companion-module-roku-tv/assets/53232897/bbc3d89a-26cb-4d4a-b8c7-d67668d7f5bf)

Here is the dropdown as it should be in 3.1.2:

![422841250_10224182011233654_3961792388218560412_n](https://github.com/bitfocus/companion-module-roku-tv/assets/53232897/a892852e-ee44-40d3-99f0-e1817b2d0f73)

Thank you!

**Comment by josephdadams** [comment]
fixed in v2.0.3 of the module
