### ISSUE TITLE
3.2.2 Unknown stop

### ISSUE THREAD

**Issue by ldhall1856** [bitfocus/companion-module-roku-tv#13]
Hi, I use multiple roku tv modules an it worked great on 3.1.2 but ever sense 3.2 i've had multiple issues.  

It says, "Waiting for connection to start... "

would greatly appreciate any help.

**Comment by josephdadams** [comment]
I don't know what version of the module you are using. Please click on the ? next to the roku instance in Connections tab and it will report the module version. That is all I really care about. Telling me Companion v3.1.2 or v3.2 does not tell me the module version.

**Comment by ldhall1856** [comment]
sorry about that. 

version v2.0.3 is the version i'm having issues with. Version v1.0.3 works great!

**Comment by josephdadams** [comment]
If you click on the >_ icon next to the Roku instance in the connections tab, it opens a new window with a log. Any errors there?

have you tried deleting and recreating the instance?

**Comment by ldhall1856** [comment]
[module-log-3_11_2024-11_17_40 AM.csv](https://github.com/bitfocus/companion-module-roku-tv/files/14561476/module-log-3_11_2024-11_17_40.AM.csv)

Log attached

**Comment by josephdadams** [comment]
This is the error: connect EADDRNOTAVAIL 192.168.35.135:8060

I am not sure why it is happening though. Maybe it is promise-related.

Does it happen after awhile? If you close out Companion and re open it, disable all roku instances except for one, and see if it happens after while, or immediately?

**Comment by ldhall1856** [comment]
Sorry for the delay.

I have restarted, and still have the issues. Stopped all the instances except one.  And still the same result. If i'm at the config of an instance. after i save it and click back on that one instance that i have running it says "Failed to load connection info: "TimeoutError: Timed out after 5s" "

 If i can give you any logs that would help trouble shoot please let me know!

**Comment by markjon** [comment]
I'm seeing the same, whether one or multiple instances enabled. Log from connection startup to when it crashes attached.
[module-log-3_24_2024-5_46_30 PM.csv](https://github.com/bitfocus/companion-module-roku-tv/files/14737606/module-log-3_24_2024-5_46_30.PM.csv)

**Comment by Gerdty** [comment]
I'm having the same issue. My current workaround is to just use http POST commands, but I would much prefer to use the Roku module built into Companion. Hoping this can be fixed soon...

**Comment by josephdadams** [comment]
`v2.0.5` of the module has been pushed to betas, it works on my tv :)
