### ISSUE TITLE
Feedback "Change Button Color/Text If Power Mode is X" not working

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion-module-roku-tv#15]
Using Companion 3.2.2 and hosted on MacOS 14.2.1

The only button feedback that works is whether the Connection is enabled. I can see from $(Roku-Bistro:power-mode) that pressing the button is cycling the Roku-TV from **Ready** to **PowerOn** etc. by putting the above variable in the button Text, but I can't change the Button Text or Color based on the "Power Mode: On" or "Power Mode: Off" Feedback checks.

Yes "Feedback" is enabled in the Connection settings, and I've dropped Polls to 1000ms.

**Comment by tacvideo** [comment]
The Button should be displaying "Standby" not "Ready"
![image](https://github.com/bitfocus/companion-module-roku-tv/assets/73620763/3287b791-85f5-4f64-87e5-948c60d2a485)

**Comment by josephdadams** [comment]
It is probably looking for “Off” and “On”, not “Ready” and “PowerOn”

**Comment by tacvideo** [comment]
Those are the only choices I have, “Off” and “On” are the only options available in feedbacks.

**Comment by tacvideo** [comment]
@josephdadams Any chance you can allow us to enter the appropriate "Power Mode" based on the variables we're getting back from the Interface, clearly the hard coded options provided (Off and On) are not working - the Roku I'm currently connected to shows "power-mode = Suspend".

**Comment by josephdadams** [comment]
Ok, I added `Standby`, `Ready`, and `Suspend` to `v2.0.4` of the module.
