### ISSUE TITLE
Actions not available

### ISSUE THREAD

**Issue by peppertechie** [bitfocus/companion-module-roku-tv#2]
Using 2.0.0 (6576dac-2303) on Pi4 4GB 

Roku module loads but when I go to assign a key down or up action there are no Roku options

When I select instance feedback I am able to see: 
Change Button Color if app is active
Change Button Color if input is active 

Let me know how I can help test.

**Comment by peppertechie** [comment]
I think this can be closed.  Once I had the Roku actually connected the key down actions were available.

**Comment by josephdadams** [comment]
Sorry I didn’t get back to you before. You’re correct. It pulls the actions based on what the device can do.
