### ISSUE TITLE
Module still trying to connect to TV when Disabled

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-roku-tv#3]
I have a TV that is currently disconnected. The module Errors out, even when I Disable it. I'm assuming the module is still trying to connect when Disabled? Otherwise, need to figure out why it's still erroring out when Disabled.

**Comment by josephdadams** [comment]
What version of companion are you running?

**Comment by cpuguru07** [comment]
companion-2.2.0-eb63b01f-3583-win64.exe

**Comment by josephdadams** [comment]
@cpuguru07 I tried this on my end and could not recreate it. Can you download the latest beta builds which features version `1.0.2` of this module and let me know if it is still happening? That way we are sure to be working off the same codebase. Thank you!
