### ISSUE TITLE
FEATURE REQUEST:  Direct Tuner Channel Command

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-roku-tv#5]
Would it be possible to have a command to a specific TV Tuner Channel number?  For example Channel 1.1.  Channel 2.1, Channel 120, etc.  Thank you!

**Comment by josephdadams** [comment]
This is Roku's ECP protocol: https://developer.roku.com/docs/developer-program/debugging/external-control-api.md

I didn't see set Tuner capability, only Channel Up/Down. But maybe I'm wrong, if you want to take a look.
