### ISSUE TITLE
Keyboard Search doesn't enter all characters

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion-module-roku-tv#6]
I created a button to send the string `ozark` but it only enters 2 random characters, for example`oz`, then `zk`, then `ak`, etc.  I've tried the Netflix search area, and also Disney+ and Apple+ login screens, and I get the same behavior everywhere.  I'm using module version 1.0.3 on Companion 2.3.0.  Roku Ultra 11.0.
If I instead try to send just 2 characters like `ab` then it sends just one, randomly either `a` or `b`.

**Comment by josephdadams** [comment]
It’s probably sending too fast. I know it’s annoying but try to send one char at a time with delays between. We could patch the module if that fixes it

**Comment by llamafilm** [comment]
Good call, thanks for the quick response!  It works with a delay.  It seems like 30ms is the minimum needed.

**Comment by josephdadams** [comment]
PR?

**Comment by josephdadams** [comment]
I implemented this
