### ISSUE TITLE
"This module has not been updated for Companion 3.0, and may not work fully"

### ISSUE THREAD

**Issue by paulstalvey** [bitfocus/companion-module-roku-tv#9]
Can confirm that the connection to a Roku TV is not very reliable.  Currently on 3.0.1 (3.0.1+6068-stable-a05a9c89) running on companion pi.

Not sure of the conditions but seems to just randomly lose connection to the TV after a while.   A fresh Companion restart seems to resolve the issue temporarily.  Never had a problem on versions prior to 3.

Going to try turning off Feedbacks to see if that helps.  Will report back next week.

**Comment by josephdadams** [comment]
I started converting it to the new v3 API but have not had time to finish it.

**Comment by paulstalvey** [comment]
Ok.  Thanks.

**Comment by pmboomer** [comment]
@josephdadams Thank you for taking the time to update the API. It's much appreciated! We're having the same challenges @paulstalvey is having. Seriously, thank you!

**Comment by TonyV66** [comment]
Would love to have an updated ROKU module for v3.  Currently, I get an error stating that it can't obtain the active app from the ROKU device.

**Comment by paulstalvey** [comment]
For anyone else having issues with this module, you may want to try the "Generic: HTTP Request" module with Roku ECP. Docs here:  https://developer.roku.com/docs/developer-program/dev-tools/external-control-api.md 

We only needed to turn our TV on, off and set an input.  E.g.  /keypress/PowerOn, /keypress/PowerOff, /keypress/InputHDMI1.   Simple and works great!

**Comment by josephdadams** [comment]
I am almost done converting it and adding some new features. Just have to test it with my Rokus.

**Comment by josephdadams** [comment]
pushing the code to the repo now if you want to test it
